apiVersion: v1
kind: LimitRange
metadata:
  name: memory-limit
spec:
  limits:
    - default:
        memory: 5Gi
      defaultRequest:
        memory: 5Gi
      max:
        memory: 10Gi
      min:
        memory: 1Gi
      type: Container
